// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import BarChartOutlined from '/Users/wangzhiyuan/Desktop/Projects/BI Platform/K-BI-Frontend/node_modules/@ant-design/icons/es/icons/BarChartOutlined';
import PieChartOutlined from '/Users/wangzhiyuan/Desktop/Projects/BI Platform/K-BI-Frontend/node_modules/@ant-design/icons/es/icons/PieChartOutlined';
import CrownOutlined from '/Users/wangzhiyuan/Desktop/Projects/BI Platform/K-BI-Frontend/node_modules/@ant-design/icons/es/icons/CrownOutlined';
export default { BarChartOutlined, PieChartOutlined, CrownOutlined };
